# Setup
title:               'Işılay Gunay'
tagline:             'Işılay Gunay'ın Web Bloğu'
description:         ''
url:                 https://isilaygunay.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Işılay Günay
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
